cafe_crawling_project/cafeproject/cafeinformation/urls.py
from django.urls import path

from . import views

app_name = 'cafe'

urlpatterns = [
    path('',views.index,name='index'),
    path('detail/',views.detail,name='detail'),
    path('preview/<int:id>/',views.preview,name='preview'),
    path('seoul/',views.seoul,name='seoul'),
    
]


cafe_crawling_project/cafeproject/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("cafe/", include('cafeinformation.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe_crawling_project/cafeproject/cafeinformation/models.py
# models.py
from django.db import models

class CsvFile(models.Model):
    file_name = models.CharField(max_length=255)
    file = models.FileField(upload_to='uploads/')

class SeoulCafeList(models.Model):
    name = models.CharField(max_length=255)
    gu = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    cafe_class = models.CharField(max_length=255)
    cafe_menu = models.TextField()
    review_count = models.CharField(max_length=255)
    review_top3 = models.TextField()
    background_image_url = models.URLField()

    def __str__(self):
        return self.name

cafe_crawling_project/cafeproject/cafeinformation/forms.py
from django import forms
from .models import CsvFile

class CsvFileForm(forms.ModelForm):
    class Meta:
        model = CsvFile
        fields = ['file_name','file']
        
class FileSelectForm(forms.Form):
    file_choices = [
        (file.id, file.file_name[9:12]) if len(file.file_name) == 16
        else (file.id, file.file_name[9:11]) if len(file.file_name) == 15
        else (file.id, file.file_name[9:13]) if len(file.file_name) == 17
        else None
        for file in CsvFile.objects.all()
    ]

    # None을 제외한 값만 선택지에 포함
    file_choices = [choice for choice in file_choices if choice is not None]

    file = forms.ChoiceField(choices=[('', '선택하세요')] + file_choices, widget=forms.Select(attrs={'class': 'form-select'}))

cafe_crawling_project/cafeproject/cafeinformation/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from .models import CsvFile,SeoulCafeList
from .forms import FileSelectForm
from django.http import HttpResponse
# Create your views here.


def index(request):
    return render(request,'cafeinformation/index.html')


class FileList(generic.ListView):
    model = CsvFile
    template_name='cafeinformation/list.html'


def detail(request):
    form = FileSelectForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        selected_file_id = form.cleaned_data['file']
        detail_data = CsvFile.objects.get(id=selected_file_id)   
        
        if len(detail_data.file_name) == 15:
            detail_data_name = detail_data.file_name[9:11]
        elif len(detail_data.file_name) == 16:
            detail_data_name = detail_data.file_name[9:12]
        elif len(detail_data.file_name) == 17:
            detail_data_name = detail_data.file_name[9:13]

        return render(request, 'cafeinformation/detail_download.html', {'detail_data': detail_data,'detail_data_name':detail_data_name})
    
    return render(request, 'cafeinformation/detail.html', {'form': form})

def seoul(request):
    seoul_data = CsvFile.objects.get(id=15)
    return render(request,'cafeinformation/seoul.html',{'seoul_data':seoul_data})

def preview(request,id):
    detail_data = CsvFile.objects.get(id=id)
    detail_data_name = detail_data.file_name
    if id == 1:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='강남구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_review_top3):
            preview.review_top3 = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
            
        print(preview_menu)
        return render(request,'cafeinformation/preview.html',{'previews':previews,'detail_data_name':detail_data_name,'detail_data':detail_data,'preview_menu':preview_menu})
    elif id == 2:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='강동구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_review_top3):
            preview.review_top3 = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        return render(request,'cafeinformation/preview.html',{'previews':previews,'detail_data_name':detail_data_name,'detail_data':detail_data})
    elif id == 3:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='강북구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_review_top3):
            preview.review_top3 = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        return render(request,'cafeinformation/preview.html',{'previews':previews,'detail_data_name':detail_data_name,'detail_data':detail_data})
    elif id == 4:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='강서구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_review_top3):
            preview.review_top3 = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        return render(request,'cafeinformation/preview.html',{'previews':previews,'detail_data_name':detail_data_name,'detail_data':detail_data})
    elif id == 5:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='관악구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_review_top3):
            preview.review_top3 = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        return render(request,'cafeinformation/preview.html',{'previews':previews,'detail_data_name':detail_data_name,'detail_data':detail_data})
    elif id == 6:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='광진구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_review_top3):
            preview.review_top3 = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        return render(request,'cafeinformation/preview.html',{'previews':previews,'detail_data_name':detail_data_name,'detail_data':detail_data})
    elif id == 7:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='구로구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_review_top3):
            preview.review_top3 = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        return render(request,'cafeinformation/preview.html',{'previews':previews,'detail_data_name':detail_data_name,'detail_data':detail_data})
    elif id == 8:
        detail_data_name = detail_data_name[9:12]
        previews = SeoulCafeList.objects.filter(gu='금천구')
        preview_menu = [preview.cafe_menu.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]

        # previews의 각 객체의 cafe_menu 필드를 가공된 값으로 변경
        for preview, formatted_menu in zip(previews, preview_menu):
            preview.cafe_menu = formatted_menu

        # 변경된 값을 저장
        for preview in previews:
            preview.save()
        
        preview_review_top3 = [preview.review_top3.replace('[','').replace(']','').replace('\'','').replace(',',' / ') for preview in previews]
        # previews의 각 객체의 review_top3 필드를 가공된 값으로 변경

cafe_crawling_project/cafeproject/cafeinformation/templates/cafeinformation/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock  %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    
    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
        }
        div{
            position: relative;
            top: 60px;
        }
        #btn{
            position: fixed;
            bottom: 20px;
            right: 13%;
        }

    </style>
    {% block head %}{% endblock  %}
</head>

<body>
    {% block top %}{% endblock  %}
    {% block content %}{% endblock  %}
    {% block bottom %}{% endblock  %}
</body>
</html>

cafe_crawling_project/cafeproject/cafeinformation/templates/cafeinformation/detail.html
{% extends "cafeinformation/base.html" %}
{% block content %}
    <div class="container" style="width: 500px;">
        <table class="table table-striped">
            <tr>
                <th colspan="2">구선택</th>
            </tr>
            <tr>
                <form method="post">
                <th>
                    {{ form.file }}
                </th>
                <th>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">확인</button>
                    </form>
                </th>
            </tr>
            <tr>
                <th colspan="2">
                    <form action="{% url 'cafe:seoul' %}">
                        <button type="submit" class="btn btn-primary">서울시 전체</button>
                    </form>
                </th>

            </tr>
            <tr>
                <th colspan="2">
                    <form action="{% url 'cafe:index' %}">
                        <button type="submit" class="btn btn-danger">뒤로가기</button>
                    </form>
                </th>
            </tr>
        </table>
    </div>
{% endblock %}

cafe_crawling_project/cafeproject/cafeinformation/templates/cafeinformation/detail_download.html
{% extends "cafeinformation/base.html" %}
{% block content %}
    <div class="container" style="width: 600px;" >
        <table class="table table-striped">
            <tr>
                <th>자치구</th>
                <th>{{ detail_data_name }}</th>
            </tr>
            <tr>
                <td colspan="2">
                    <a href="{{ detail_data.file.url }}" download>
                        다운로드
                    </a>
                </td>
            </tr>
            <tr>
                <form action="{% url 'cafe:preview' detail_data.id %}">
                    <th colspan="2">
                        <button type="submit" class="btn btn-primary">다운로드 파일 미리보기
                        </button>
                    </th>
                </form>
            </tr>
                <tr>
                <th colspan="2">
                    <form action="{% url 'cafe:detail' %}">
                        <button type="submit" class="btn btn-danger">
                            뒤로가기
                        </button>
                    </form>
                </th>
            </tr>
        </table>
    <div>
        
{% endblock %}

cafe_crawling_project/cafeproject/cafeinformation/templates/cafeinformation/index.html
{% extends "cafeinformation/base.html" %}
{% block content %}
    <div class="container" style="width: 500px;">
        <table class="table table-striped">
            <tr>
                <th colspan='2'>메인화면</th>
            </tr>
            <tr>
                <th>
                    파일목록
                </th>
            </tr>
            <tr>
                <form action="{% url 'cafe:detail' %}" class="mt-3">
                    <td colspan="2">
                        <button type="submit" class="btn btn-primary">보기</button>
                    </td>
                </form>
            </tr>
        </table>
    </div>
{% endblock  %}

cafe_crawling_project/cafeproject/cafeinformation/templates/cafeinformation/preview.html
{% extends "cafeinformation/base.html" %}
{% block head %}
<style>
    #preview{
        text-align: left;
    }
    th, td {
        text-align: left;
    }
</style>
{% endblock  %}
{% block content %}
    <div class="container" style="width: 1200px;" >
        <table class="table table-striped" id="preview">
            <tr>
                <th id="top">자치구</th>
                <th style="text-align: center;">{{ detail_data_name }}</th>
                <th style="text-align: center;">
                    <form action="{% url 'cafe:detail' %}">
                        <button type="submit" class="btn btn-danger" style="height: 40px; width:100px">
                            <span style="font-size: 15px;">
                                뒤로가기
                            </span>
                        </button>
                    </form>
                </th>
            </tr>
            <tr>
                <td colspan="3" style="text-align: center;">
                    <a href="{{ detail_data.file.url }}" download>
                        다운로드
                    </a>
                </td>
            </tr>
            {% for data in previews %}
                <tr>
                    <th colspan="3" style="text-align: center;">
                        -----------------------------{{ forloop.counter }}번째-----------------------------
                    </th>
                </tr>
                <tr>
                    <th style="width: 100px;">
                        카페이름   
                    </th>
                    <th colspan="2">
                        <a href="https://map.naver.com/p/search/{{ data.name }}" target="_blank">{{ data.name }}</a>

                    </th>
                </tr>
                <tr>
                    <th>
                        카페종류
                    </th>
                    <th colspan="2">
                        {{ data.cafe_class }}
                    </th>
                </tr>
                <tr>
                    <th>
                        리뷰개수
                    </th>
                    <th colspan="2">
                        {{ data.review_count}}
                    </th>
                </tr>
                <tr>
                    <th>
                        카페주소
                    </th>
                    <th colspan="2">
                        {{ data.address }}
                    </th>
                </tr>
                <tr>
                    <th style="text-align: center;">
                        리뷰TOP3
                    </th>
                    <th colspan="2">
                        {{ data.review_top3}}
                    </th>
                </tr>
                <tr>
                    <th>
                        카페사진
                    </th>
                    <th colspan="2" style="text-align: center;">
                        <img src="{{ data.background_image_url }}" alt="{{ data.name }}" style="width: 300px;">
                    </th>
                </tr>
                <tr>
                    <th>
                        카페메뉴
                    </th>
                    <th colspan="2">
                        {{ data.cafe_menu }}
                    </th>
                </tr>
            {% endfor %}
        </table>
        <div>
        <p>
            <a href="{% url 'cafe:preview' detail_data.id %}#top" class="btn btn-primary" id="btn">
            맨 위로
            </a>
        </p>

        
{% endblock %}

cafe_crawling_project/cafeproject/cafeinformation/templates/cafeinformation/seoul.html
{% extends "cafeinformation/base.html" %}
{% block content %}
    <div class="container" style="width: 600px;" >
        <table class="table table-striped">
            <tr>
                <th colspan="2">서울전체</th>
            </tr>
            <tr>
                <td colspan="2">
                    <a href="{{ seoul_data.file.url }}" download>
                        다운로드
                    </a>
                </td>
            </tr>
            <tr>
                <form action="{% url 'cafe:preview' seoul_data.id %}">
                    <th colspan="2">
                        <button type="submit" class="btn btn-primary">다운로드 파일 미리보기
                        </button>
                    </th>
                </form>
            </tr>
                <tr>
                <th colspan="2">
                    <form action="{% url 'cafe:detail' %}">
                        <button type="submit" class="btn btn-danger">
                            뒤로가기
                        </button>
                    </form>
                </th>
            </tr>
        </table>
    <div>
        
{% endblock %}