Piching_info/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('player_info.urls')),
]

Piching_info/player_info/urls.py
from django.urls import path
from player_info import views

app_name = 'pitch'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('playerinfo/', views.Player.as_view(), name='player'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('pitching/<int:id>/', views.pitching, name="pitching"),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('pitching_avg/<int:id>/', views.pitching_avg, name='pitching_avg'),
    path('vsinfo/<int:id>/', views.vsinfo, name='vsinfo'),
    path('gamedetail/<int:id>/<int:pk>/', views.gamedetail, name='gamedetail'),
    path('delete_opponent/<int:id>/<int:pk>', views.delete_opponent, name='delete_opponent'),
    path('update/<int:pk>/<int:id>/', views.update, name='update'),
    
    
]

Piching_info/player_info/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class PlayerInfo(models.Model):
    schoolname = models.CharField(max_length=50)
    grade = models.CharField(max_length=50)
    playername = models.CharField(max_length=50)
    age = models.IntegerField(null=False)
    pitchingtype = models.CharField(max_length=20)
    intro = models.TextField(max_length=2000)
    pub_date = models.DateTimeField("date published", auto_now_add=True)

    def __str__(self):
        return f'소속 : {self.schoolname}, 학년 : {self.grade} 이름 : {self.playername}, 유형 : {self.pitchingtype}'
    
class Opponent(models.Model):
    gamename = models.CharField(max_length=50)
    opponent_name = models.CharField(max_length=20)
    opponent_date = models.DateTimeField(default='')
    playerinfo_reference = models.ForeignKey(PlayerInfo, on_delete=models.CASCADE)
    

class Record(models.Model):
    opponent_reference = models.ForeignKey(Opponent, on_delete=models.CASCADE)
    record = models.CharField(default='',max_length=100)
    position = models.CharField(default='',max_length=100)
    speed = models.IntegerField(default=135)
    ballcourse = models.IntegerField(default=0)
    strike_ball = models.CharField(default='',max_length=10)
    hitter_num = models.IntegerField(default=0)

class BallData(models.Model):
    opponent = models.ForeignKey(Opponent, on_delete=models.CASCADE)
    total_pitches = models.IntegerField(default=0)
    total_fast_ball = models.IntegerField(default=0)
    total_breaking_ball= models.IntegerField(default=0)
    total_speed_off_ball= models.IntegerField(default=0)

    foursim_ball = models.IntegerField(default=0)
    twosim_ball = models.IntegerField(default=0)
    cutfast_ball = models.IntegerField(default=0)

    curve_ball = models.IntegerField(default=0)
    slider_ball = models.IntegerField(default=0)
    sinker_ball = models.IntegerField(default=0)

    circlechan_ball = models.IntegerField(default=0)
    splitter_ball = models.IntegerField(default=0)
    fork_ball = models.IntegerField(default=0)
    
    left_hitter_total_pitches = models.IntegerField(default=0)
    left_hitter_total_fast_ball = models.IntegerField(default=0)
    left_hitter_total_breaking_ball = models.IntegerField(default=0)
    left_hitter_total_speed_off_ball = models.IntegerField(default=0)
    
    right_hitter_total_pitches = models.IntegerField(default=0)
    right_hitter_total_fast_ball = models.IntegerField(default=0)
    right_hitter_total_breaking_ball = models.IntegerField(default=0)
    right_hitter_total_speed_off_ball = models.IntegerField(default=0)


    

Piching_info/player_info/forms.py
from django import forms
from .models import PlayerInfo,Opponent,Record

class PlayerInfoForm(forms.ModelForm):
    class Meta:
        model = PlayerInfo
        fields = ['schoolname','grade','playername','age','pitchingtype','intro']
        widgets = {
            'intro':forms.Textarea(attrs={'rows': 7, 'cols':30,'placeholder':'입력 하세요'}),
            
            'schoolname':forms.TextInput(attrs={'placeholder':'00고등학교'}),
    
            'playername':forms.TextInput(attrs={'placeholder':'홍길동'}),
            
            'age':forms.TextInput(attrs={'placeholder':'17'}),
            
            'pitchingtype':forms.TextInput(attrs={'placeholder':'R/O (Right/Over hand)'}),
        }

class SpeedForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['speed']
        widgets = {
            'speed':forms.NumberInput(attrs={'style':'width: 100px'})
        }

class OpponentForm(forms.ModelForm):
    class Meta:
        model = Opponent
        fields = ['opponent_date','opponent_name']
        widgets = {
            'opponent_date': forms.DateTimeInput(
                attrs={'type': 'datetime-local'},
                format='%Y-%m-%dT%H:%M'
            ),
            'opponent_name':forms.TextInput(attrs={'placeholder':'00고등학교'}),
        }

    

    


Piching_info/player_info/views.py
from django.shortcuts import render, redirect
from .models import PlayerInfo, BallData,Opponent,Record
from django.urls import reverse
# Create your views here.
from django.views import generic
from .forms import PlayerInfoForm,SpeedForm,OpponentForm

# 계산 여기부터

def add(ball_data,pitching_datas,leftright):
    if leftright == 'Left':
        if pitching_datas == 'foursim': 
            ball_data.foursim_ball += 1
            ball_data.total_fast_ball += 1
            ball_data.left_hitter_total_fast_ball += 1
                
        elif pitching_datas == 'twosim':
            ball_data.twosim_ball += 1
            ball_data.total_fast_ball += 1
            ball_data.left_hitter_total_fast_ball += 1
            
        elif pitching_datas == 'cutfast':
            ball_data.cutfast_ball += 1
            ball_data.total_fast_ball += 1
            ball_data.left_hitter_total_fast_ball += 1
            
        elif pitching_datas == 'curve':
            ball_data.curve_ball += 1
            ball_data.total_breaking_ball += 1
            ball_data.left_hitter_total_breaking_ball += 1
            
        elif pitching_datas == 'slider':
            ball_data.slider_ball += 1
            ball_data.total_breaking_ball += 1
            ball_data.left_hitter_total_breaking_ball += 1
            
        elif pitching_datas == 'sinker':
            ball_data.sinker_ball += 1
            ball_data.total_breaking_ball += 1
            ball_data.left_hitter_total_breaking_ball += 1
            
        elif pitching_datas == 'circlechan':
            ball_data.circlechan_ball += 1
            ball_data.total_speed_off_ball += 1
            ball_data.left_hitter_total_speed_off_ball += 1
            
        elif pitching_datas == 'splitter':
            ball_data.splitter_ball += 1
            ball_data.total_speed_off_ball += 1
            ball_data.left_hitter_total_speed_off_ball += 1
            
        elif pitching_datas == 'forkball':
            ball_data.fork_ball += 1
            ball_data.total_speed_off_ball += 1
            ball_data.left_hitter_total_speed_off_ball += 1
            
        ball_data.total_pitches += 1
        ball_data.left_hitter_total_pitches += 1
        ball_data.save()
        
    elif leftright == 'Right':
        if pitching_datas == 'foursim': 
            ball_data.foursim_ball += 1
            ball_data.total_fast_ball += 1
            ball_data.right_hitter_total_fast_ball += 1
                
        elif pitching_datas == 'twosim':
            ball_data.twosim_ball += 1
            ball_data.total_fast_ball += 1
            ball_data.right_hitter_total_fast_ball += 1
            
        elif pitching_datas == 'cutfast':
            ball_data.cutfast_ball += 1
            ball_data.total_fast_ball += 1
            ball_data.right_hitter_total_fast_ball += 1
            
        elif pitching_datas == 'curve':
            ball_data.curve_ball += 1
            ball_data.total_breaking_ball += 1
            ball_data.right_hitter_total_breaking_ball += 1
            
        elif pitching_datas == 'slider':
            ball_data.slider_ball += 1
            ball_data.total_breaking_ball += 1
            ball_data.right_hitter_total_breaking_ball += 1
            
        elif pitching_datas == 'sinker':
            ball_data.sinker_ball += 1
            ball_data.total_breaking_ball += 1
            ball_data.right_hitter_total_breaking_ball += 1
            
        elif pitching_datas == 'circlechan':
            ball_data.circlechan_ball += 1
            ball_data.total_speed_off_ball += 1
            ball_data.right_hitter_total_speed_off_ball += 1
            
        elif pitching_datas == 'splitter':
            ball_data.splitter_ball += 1
            ball_data.total_speed_off_ball += 1
            ball_data.right_hitter_total_speed_off_ball += 1
            
        elif pitching_datas == 'forkball':
            ball_data.fork_ball += 1
            ball_data.total_speed_off_ball += 1
            ball_data.right_hitter_total_speed_off_ball += 1
            
        ball_data.total_pitches += 1
        ball_data.right_hitter_total_pitches += 1
        ball_data.save()
        
def calcul(opponent_start,pitching_datas,leftright):
    ball_data = opponent_start.balldata_set.first()
    
    add(ball_data,pitching_datas,leftright)
    
# 여기까지

class Index(generic.ListView):
    model = PlayerInfo
    template_name = "player_info/index.html"


class Player(generic.CreateView):
    model = PlayerInfo
    form_class = PlayerInfoForm
    template_name= "player_info/player.html"
    success_url = '/info/'

class Detail(generic.DetailView):
    model = PlayerInfo
    template_name= "player_info/detail.html"


def pitching(request, id):
    pitching_data = PlayerInfo.objects.get(pk=id)
    
    form_class = SpeedForm
    
    gamename = request.POST['gamename']                   # 게임이름
    opponent_name = request.POST['opponent_name']         # 상대팀명
    opponent_date = request.POST['opponent_date']         # 경기날짜


    new_opponent = pitching_data.opponent_set.create(gamename=gamename,
                                      opponent_name=opponent_name,
                                      opponent_date=opponent_date) # 데이터 생성
    opponent_data = Opponent.objects.get(id=new_opponent.id)
    record_data = opponent_data.record_set.all()
    
    balldata = opponent_data.balldata_set.create()

    ctx = {'pitching_data':pitching_data,'record_data':record_data,'form_class':form_class,'opponent_data':opponent_data} #####
    
    return render(request, 'player_info/pitching.html', ctx)


def delete(request, id):
    delete_data = PlayerInfo.objects.get(pk=id)
    if request.method == 'POST':
        delete_data.delete()

        return redirect('/info/')
    
    else:
        return render(request, 'player_info/delete.html',{'delete_data':delete_data})
    

def edit(request, id):
    detail_data = PlayerInfo.objects.get(pk=id)
    if request.method == 'POST':
        detail_data.schoolname = request.POST.get('schoolname')
        detail_data.grade = request.POST.get('grade')
        detail_data.playername = request.POST['playername']
        detail_data.age = request.POST.get('age')
        detail_data.pitchingtype = request.POST.get('pitchingtype')
        detail_data.intro = request.POST.get('intro')
        detail_data.save()
        return redirect(f'/info/detail/{id}/')
    
    else:
        return render(request, 'player_info/edit.html',{'detail_data':detail_data})
 

    
def update(request,pk,id):
    pitching_data = PlayerInfo.objects.get(pk=pk)
    opponent_start = pitching_data.opponent_set.order_by('-id').first()
    form_class = SpeedForm
    
    leftright = request.POST['update_leftright']
    hitter_num = int(request.POST['update_hitter_num'])
    record_updates = opponent_start.record_set.get(pk=id)
    record_updates.record = request.POST['update_record']
    record_updates.ballcourse = request.POST['update_course']
    record_updates.speed = request.POST['update_speed']
    record_updates.position = leftright
    record_updates.strike_ball = request.POST['update_strikeball']
    record_updates.hitter_num = hitter_num
    
    record_updates.save()
    ctx = {'leftright':leftright,'pitching_data':pitching_data,'opponent_start':opponent_start,'form_class':form_class,'hitter_num':hitter_num}
    
    return render(request,'player_info/pitching.html',ctx)

def pitching_avg(request, id):
    pitching_data = PlayerInfo.objects.get(pk=id)
    opponent_start = pitching_data.opponent_set.order_by('-id').first()
    form_class = SpeedForm
    leftright = request.POST['leftright']   # 좌타 우타 값 받아오기
    hitter_num = int(request.POST['hitter_num']) # 타순 받아오기
    try:
        pitching_datas = request.POST['pitchinginfo']
        speed = request.POST['speed']           # 스피드 받아오기
        ballcourse = request.POST['ballcourse'] # 코스 받아오기
        strike_ball = request.POST['strikeball'] # 스트라크/볼 받아오기
        
        calcul(opponent_start,pitching_datas,leftright)
        opponent_start.record_set.create(record=pitching_datas,position=leftright,speed=speed,ballcourse=ballcourse,strike_ball=strike_ball,hitter_num=hitter_num)
        ctx = {'pitching_data':pitching_data,'leftright':leftright,'form_class':form_class,'opponent_start':opponent_start,'hitter_num':hitter_num}
        
        return render(request,'player_info/pitching.html',ctx)
    except:
        error_message = '구종/코스 를 선택해주세요.'
        ctx = {'error_message':error_message,'pitching_data':pitching_data,'form_class':form_class,'opponent_start':opponent_start,'hitter_num':hitter_num,'leftright':leftright}
        
        return render(request,'player_info/pitching.html',ctx)

    
from django.utils import timezone

def vsinfo(request,id):
    pitching_data = PlayerInfo.objects.get(pk=id)

    form_class = OpponentForm
    opponent_data = pitching_data.opponent_set.all()
    
    ctx = {'pitching_data':pitching_data,'opponent_data':opponent_data,'form_class':form_class}
    return render(request,'player_info/vsinfo.html',ctx)




def gamedetail(request,id,pk):
    pitching_data = PlayerInfo.objects.get(pk=pk)
    opponent_rec = Opponent.objects.get(pk=id)
    
    ball_data = opponent_rec.balldata_set.all()[0]
    if ball_data.left_hitter_total_pitches == 0:
        left_bk_per = 0
        left_so_per = 0
        left_ft_per = 0
    else:   
        left_ft_per = round(ball_data.left_hitter_total_fast_ball / ball_data.left_hitter_total_pitches * 100,1)
        left_bk_per = round(ball_data.left_hitter_total_breaking_ball / ball_data.left_hitter_total_pitches * 100,1)            

Piching_info/player_info/templates/player_info/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pitch rate of a Pitcher</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
        }
        #err{
            text-align: center;
        }
        #btn{
            position: fixed;
            bottom: 20px;
            right: 13%;
        }
        @media print {
            #btn {
            display: none;
            }   
            #first {
                page-break-before: always;
            }
        
            #secound {
                page-break-after: always;
            }
        
        }
        .clickable-td {
            cursor: pointer;
        }
    
        .selected-td {
            background-color: #f72121; /* 원하는 배경색으로 변경하세요 */
        }
        
    </style>
</head>
<body>  
    {% block top %}
        <center><h1>Pitch rate of a Pitcher</h1><hr></center>
    {% endblock %}

    {% block content %}{% endblock %}

    {% block bottom %}
    <center><hr>
        <h5>
        Pitch rate of a Pitcher test ver 0.9<br>made in J & B
        </h5>
    </center>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

Piching_info/player_info/templates/player_info/delete.html
{% extends "player_info/base.html" %}
{% block top %}<h1>
    <center>학생 정보 삭제
</h1>
<hr>
</center>{% endblock %}
{% block content %}
<div class="container" style="width: 800px;">
    <table class="table table-striped">
        <tr>
            <td>소속</td>
            <td>{{delete_data.schoolname}}</td>
        </tr>
        <tr>
            <td>이름</td>
            <td>{{delete_data.playername}}</td>
        </tr>
        <tr>
            <form action="{% url 'pitch:delete' delete_data.id %}" class="mt-3" method="POST">
                {%csrf_token%}
                <td colspan="2" style="color: red;">정말로 삭제하시겠습니까?
                    <button type="submit" class="btn btn-danger">확인</button>
            </form>
            </td>
        </tr>
        <tr>
            <form action="{% url 'pitch:detail' delete_data.id %}" class="mt-3">
                <td colspan="2">
                    <button type="submit" class="btn btn-primary">아니요</button>
                </td>
            </form>
        </tr>

    </table>
</div>
{% endblock %}

Piching_info/player_info/templates/player_info/delete_opponent.html
{% extends "player_info/base.html" %}
{% block top %}<h1>
    <center>경기기록 정보 삭제
</h1>
<hr>
</center>{% endblock %}
{% block content %}
<div class="container" style="width: 800px;">
    <table class="table table-striped">
        <tr>
            <th>대회명</th>
            <td>{{opponent_data_del.gamename}}</td>
        </tr>
        <tr>
            <th>상대팀명</th>
            <td>{{opponent_data_del.opponent_name}}</td>
        </tr>
        <tr>
            <th>경기날짜</th>
            <td>{{opponent_data_del.opponent_date}}</td>
        </tr>
        <tr>
            <form action="{% url 'pitch:delete_opponent' opponent_data_del.id pitching_data.id %}" method="POST"
                class="mt-3">
                {% csrf_token %}
                <td colspan="2" style="color: red;">정말로 삭제하시겠습니까?
                    <button type="submit" class="btn btn-danger">확인</button>
                </td>
            </form>
        </tr>
        <tr>
            <form action="{% url 'pitch:detail' pitching_data.id %}" class="mt-3">
                <td colspan="2">
                    <button type="submit" class="btn btn-primary">아니요</button>
                </td>
            </form>
        </tr>

    </table>
</div>
{% endblock %}

Piching_info/player_info/templates/player_info/detail.html
{% extends "player_info/base.html" %}
{% block top %}<center>
    <h1>상세 정보</h1>
    <hr>
</center>{% endblock %}
{% block content %}<center>

    <div class="container" style="width:650px;">
        <table class="table table-striped">
            <tr>
                <th>소속</th>
                <td>{{object.schoolname}}</td>
            </tr>
            <tr>
                <th>학년</th>
                <td>{{object.grade}}</td>
            </tr>
            <tr>
                <th>이름</th>
                <td>{{object.playername}}</td>
            </tr>
            <tr>
                <th>나이</th>
                <td>{{object.age}}</td>
            </tr>
            <tr>
                <th>유형</th>
                <td>{{object.pitchingtype}}</td>
            </tr>
            <tr>
                <th>특이사항</th>
                <td>{{object.intro}}</td>
            </tr>
        </table>
        <hr>
        <h1>
            경기 기록
        </h1>
        <hr>
        <table class="table table-striped">
            <tr>
                <td>번호</td>
                <td>대회명</td>
                <td>상대팀명</td>
                <td>경기날짜</td>
                <td>상세보기</td>
                <td>삭제</td>
            </tr>
            {% for opponent in object.opponent_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ opponent.gamename }}</td>
                <td>{{ opponent.opponent_name }}</td>
                <td>{{ opponent.opponent_date }}</td>
                <form action="{% url 'pitch:gamedetail' opponent.id object.id %}" class="mt-3">
                    <td>
                        <button type="submit" class="btn btn-primary">보기</button>
                    </td>
                </form>
                <form action="{% url 'pitch:delete_opponent' opponent.id object.id %}" class="mt-3">
                    {%csrf_token%}
                    <td>
                        <button type="submit" class="btn btn-danger">삭제</button>
                    </td>
                </form>
            </tr>
            {% endfor %}
        </table>

        <form action="{% url 'pitch:edit' object.id %}" class="mt-3">
            <button type="submit" class="btn btn-primary">수정하기</button>
        </form>
        <form action="{% url 'pitch:delete' object.id %}" class="mt-3">
            <button type="submit" class="btn btn-danger">삭제하기</button>
        </form>
        <form action="{% url 'pitch:index' %}" class="mt-3">
            <button type="submit" class="btn btn-primary">목록으로 돌아가기</button>
        </form>

        {% endblock %}

Piching_info/player_info/templates/player_info/edit.html
{% extends "player_info/base.html" %}
{% block top %}<center><h1>정보 수정</h1></center><hr>{% endblock %}

{% block content %}
<form action="{% url 'pitch:edit' detail_data.id %}" method="POST">
    {% csrf_token %}
    <div class="container" style="width: 510px;">
        <table class="table table-striped">
            <tr>
                <th>소속</th>
                <td style="text-align: left;">
                    <input type="text" name="schoolname" value="{{detail_data.schoolname}}" required>
                </td>
            </tr>
            <tr>
                <th>학년</th>
                <td style="text-align: left;">
                    <select name="grade" value="{{detail_data.grade}}">
                        <option value="1학년">1학년</option>
                        <option value="2학년">2학년</option>
                        <option value="3학년">3학년</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th >이름</th>
                <td style="text-align: left;">
                    <input type="name" name="playername" value="{{detail_data.playername}}" required>
                </td>
            </tr>
            <tr>
                <th >나이</th>
                <td style="text-align: left;">
                    <input type="text" name="age" value="{{detail_data.age}}" required>
                </td>
            </tr>
            <tr>
                <th>유형</th>
                <td style="text-align: left;">
                    <input type="text" name="pitchingtype" value="{{detail_data.pitchingtype}}" required>
                </td>
            </tr>
            <tr>
                <th>특이사항</th>
                <td style="text-align: left;">
                    <textarea name="intro" rows='7' cols='30'>{{detail_data.intro}}</textarea>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" value="수정하기" class="btn btn-primary">
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <a href="{% url 'pitch:index' %}" class="btn btn-primary">목록으로 돌아가기</a>
                </td>
            </tr>
        </table>
    </div>
</form>
{% endblock %}


Piching_info/player_info/templates/player_info/fail.html
{% extends "player_info/base.html" %}

{% block content %}
<form method="POST" class="mt-3">
    {% csrf_token %}
    <div class="container" style="width: 510px;">
        <table class="table table-striped">
            <tr>
                <th colspan="2">
                    <h3>
                    경기 기록이 없습니다
                </h3>
            </th>
            </tr>
            <tr>
                <div class="container" style="width: 510px; text-align: center; margin-top: 10px;">
                <th colspan="2">
                        <a href="{% url 'pitch:index' %}" class="btn btn-primary">목록으로 돌아가기</a>
                    </div>
                </th>
            </tr>
        </table>
    </div>
</form>
{% endblock %}

Piching_info/player_info/templates/player_info/index.html
{% extends "player_info/base.html" %}

{% block content %}
    <center>
        <form action="{% url 'pitch:player' %}" class="mb-3">
            <button type="submit" class="btn btn-danger">정보 추가하기</button>
        </form>
    </center>

    <div class="container" style="width: 800px;">
        {% for info in object_list %}
            <table class="table table-striped">
                <tr>
                    <th style="width: 230px;">학교명</th>
                    <td>{{info.schoolname}}</td>
                </tr>
                <tr>
                    <th style="width: 100px;">이름</th>
                    <td>{{info.playername}}</td>
                </tr>
                <tr>
                    <th style="width: 200px;">학년 / 유형</th>
                    <td>{{info.grade}}
                        /
                        {{info.pitchingtype}}</td>
                </tr>
                <tr>
                    <th style="width: 300px;">정보 등록일</th>
                    <td>{{info.pub_date}}</td>
                </tr>
                <tr>
                    <div class="container" style="width: 510px; text-align: center; margin-top: 10px;">
                        <th colspan="2">
                            <a href="{% url 'pitch:detail' info.id %}" class="btn btn-primary"
                            >상세 정보
                        </a>
                        <a href="{% url 'pitch:vsinfo' info.id %}" class="btn btn-primary"
                            >피칭 시작
                        </a>
                        </th>
                    </div>
                </tr>
            </table>
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}



Piching_info/player_info/templates/player_info/player.html
{% extends "player_info/base.html" %}
{% block top %}<center><h1>선수 정보 입력</h1><hr></center>{% endblock %}

{% block content %}
<form method="POST" class="mt-3">
    {% csrf_token %}
    <div class="container" style="width: 510px;">
        <table class="table table-striped">
            <tr style="text-align: left;">
                <th>소속</th>
                <td style="text-align: left;">{{ form.schoolname }}</td>
            </tr>
            <tr>
                <th>학년</th>
                <td style="text-align: left;">
                    <select name="grade">
                    <option value="1학년">1학년</option>
                    <option value="2학년">2학년</option>
                    <option value="3학년">3학년</option>
                </select>
            </td>
            </tr>
            <tr>
                <th>이름</th>
                <td style="text-align: left;">{{ form.playername }}</td>
            </tr>
            <tr>
                <th>나이</th>
                <td style="text-align: left;">{{ form.age }}</td>
            </tr>
            <tr>
                <th>유형</th>
                <td style="text-align: left;">{{ form.pitchingtype }}</td>
            </tr>
            <tr>
                <th>특이사항</th>
                <td style="text-align: left;">{{ form.intro }}</td>
            </tr>
            <tr>
                <th colspan="2">
                    <button type="submit" class="btn btn-primary">등록</button>
                </th>
            </tr>
            <tr>
                <div class="container" style="width: 510px; text-align: center; margin-top: 10px;">
                <th colspan="2">
                        <a href="{% url 'pitch:index' %}" class="btn btn-primary">목록으로 돌아가기</a>
                    </div>
                </th>
            </tr>
        </table>
    </div>
</form>
{% endblock %}

Piching_info/player_info/templates/player_info/vsinfo.html
{% extends "player_info/base.html" %}
{% block top %}
<center>
    <h1>상대 팀 정보</h1>
    <hr>
</center>
{% endblock %}

{% block content %}
<form action="{% url 'pitch:pitching' pitching_data.id %}" method="post">
    {% csrf_token %}
    <div class="container" style="width: 800px;">
        <table class="table table-striped">
            <tr>
                <th>대회 이름</th>
                <th>상대팀 명</th>
                <th>경기날짜</th>
            </tr>
            <tr>
                <th>
                    <select name="gamename">
                        <option value="연습경기">연습경기</option>
                        <option value="이마트배">신세계 이마트배</option>
                        <option value="황금사자기">황금사자기</option>
                        <option value="대통령배">대통령배</option>
                        <option value="청룡기">청룡기</option>
                        <option value="봉황기">봉황기</option>
                        <option value="전국체육대회">전국체육대회</option>
                        <option value="전반기 주말리그">전반기 주말리그</option>
                        <option value="후반기 주말리그">후반기 주말리그</option>
                    </select>
                </th>
                <th>
                    {{ form_class.opponent_name }}
                </th>
                <th>
                    {{ form_class.opponent_date }}
                </th>
            </tr>
        </table>
        <center>
            <button type="submit" class="btn btn-primary">피칭시작</button>
        </center>
</form>
<hr>
<table class="table table-striped">
    <tr>
        <td>번호</td>
        <td>대회명</td>
        <td>상대팀명</td>
        <td>경기날짜</td>
    </tr>
    {% for opponent in pitching_data.opponent_set.all %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ opponent.gamename }}</td>
        <td>{{ opponent.opponent_name }}</td>
        <td>{{ opponent.opponent_date }}</td>
    </tr>
    {% endfor %}
</table>
<div class="container" style="width: 510px; text-align: center; margin-top: 10px;">
    <th colspan="2">
        <a href="{% url 'pitch:index' %}" class="btn btn-primary">목록으로 돌아가기</a>
    </th>
</div>
</div>
{% endblock %}